export const EXHIBITOR_PHOTOS_THEMED: Record<string, { light: ReturnType<typeof require>; dark: ReturnType<typeof require> }> = {
  'biz_016': {
    light: require('@/assets/images/exhibitors/sponsors/unesco_natcom_esp_flag_spa_W.png'),
    dark: require('@/assets/images/exhibitors/sponsors/unesco_natcom_esp_flag_spa_B.png'),
  },
};

export function getExhibitorPhoto(id: string, scheme: 'light' | 'dark'): ReturnType<typeof require> | undefined {
  if (EXHIBITOR_PHOTOS_THEMED[id]) return EXHIBITOR_PHOTOS_THEMED[id][scheme];
  return EXHIBITOR_PHOTOS[id];
}

export const EXHIBITOR_PHOTOS: Record<string, ReturnType<typeof require>> = {
  // Speakers & Committee
  'spk_001': require('@/assets/images/exhibitors/speakers/antonio ferrer montiel.jpg'),
  'spk_002': require('@/assets/images/exhibitors/speakers/Benedetta bolognesi.jpg'),
  'spk_003': require('@/assets/images/exhibitors/speakers/benjami_oller-salvia.jpg'),
  'spk_004': require('@/assets/images/exhibitors/speakers/Juan J. calvete.jpg'),
  'spk_005': require('@/assets/images/exhibitors/speakers/nuria sanchez coll.jpg'),
  'spk_006': require('@/assets/images/exhibitors/speakers/Silvia Osuna.jpg'),
  'spk_007': require('@/assets/images/exhibitors/SIN_FOTO.png'),
  'spk_008': require('@/assets/images/exhibitors/SIN_FOTO.png'),
  'spk_009': require('@/assets/images/exhibitors/speakers/CarlaLopez.jpg'),
  'spk_010': require('@/assets/images/exhibitors/speakers/Enrique Asin-Garcia.jpg'),
  'spk_011': require('@/assets/images/exhibitors/speakers/Martin Floor.jpg'),
  'spk_012': require('@/assets/images/exhibitors/speakers/francesc godia.jpg'),
  'spk_013': require('@/assets/images/exhibitors/speakers/Elisabet Engel Lopez.jpg'),
  'spk_014': require('@/assets/images/exhibitors/speakers/Marta Cascante.jpg'),
  'spk_015': require('@/assets/images/exhibitors/speakers/albert font ingles.jpg'),
  'spk_016': require('@/assets/images/exhibitors/speakers/ariadna grau.png'),
  'spk_017': require('@/assets/images/exhibitors/speakers/avencia sanchez-mejias.jpg'),
  'spk_018': require('@/assets/images/exhibitors/speakers/cote falaguera.jpg'),
  'spk_019': require('@/assets/images/exhibitors/speakers/estella buscato.png'),
  'spk_020': require('@/assets/images/exhibitors/speakers/gerard caelles.jpg'),
  'spk_021': require('@/assets/images/exhibitors/speakers/joan domingo.png'),
  'spk_022': require('@/assets/images/exhibitors/speakers/jordi ruano.jpg'),
  'spk_023': require('@/assets/images/exhibitors/speakers/jordi xiol.jpg'),
  'spk_024': require('@/assets/images/exhibitors/speakers/laure burtin.jpeg'),
  'spk_025': require('@/assets/images/exhibitors/speakers/luis ruiz-avila.png'),
  'spk_026': require('@/assets/images/exhibitors/speakers/marta figa.jpg'),
  'spk_027': require('@/assets/images/exhibitors/speakers/paqui escoi.png'),
  'spk_028': require('@/assets/images/exhibitors/speakers/julia garcia.jpg'),
  'spk_029': require('@/assets/images/exhibitors/SIN_FOTO.png'),
  'spk_030': require('@/assets/images/exhibitors/speakers/mariona.jpg'),
  'spk_031': require('@/assets/images/exhibitors/speakers/miguel_galan.jpg'),
  'spk_033': require('@/assets/images/exhibitors/SIN_FOTO.png'),
  'spk_034': require('@/assets/images/exhibitors/speakers/FotoAmolina - Antonio Molina.png'),
  'spk_035': require('@/assets/images/exhibitors/speakers/Lara Cobacho Lluesma.jpg'),
  'spk_036': require('@/assets/images/exhibitors/speakers/LucaCaprera.jpg'),
  'spk_037': require('@/assets/images/exhibitors/speakers/MariaLois.jpg'),
  'spk_038': require('@/assets/images/exhibitors/speakers/JuanCarlos.jpg'),
  'spk_039': require('@/assets/images/exhibitors/speakers/Xavier_Aldeguer.jpg'),
  'spk_040': require('@/assets/images/exhibitors/speakers/xavier_rovira.jpg'),
  'spk_041': require('@/assets/images/exhibitors/speakers/JordiMartorell.jpg'),
  'spk_042': require('@/assets/images/exhibitors/speakers/RocioVazquez.jpg'),
  'spk_043': require('@/assets/images/exhibitors/SIN_FOTO.png'),
  'spk_044': require('@/assets/images/exhibitors/SIN_FOTO.png'),
  'spk_045': require('@/assets/images/exhibitors/SIN_FOTO.png'),
  'spk_046': require('@/assets/images/exhibitors/SIN_FOTO.png'),
  'spk_047': require('@/assets/images/exhibitors/SIN_FOTO.png'),
  'spk_048': require('@/assets/images/exhibitors/SIN_FOTO.png'),
  'spk_178': require('@/assets/images/exhibitors/speakers/Gemma Marfany.png'),
  'spk_179': require('@/assets/images/exhibitors/speakers/Marco Mariotti.png'),
  'spk_180': require('@/assets/images/exhibitors/speakers/Aroa Casado.jpg'),
  'spk_181': require('@/assets/images/exhibitors/speakers/Luis G. Merida.png'),
  'cc_001': require('@/assets/images/exhibitors/speakers/Eliana Carolina Bianucci Ovando.jpg'),
  'cc_002': require('@/assets/images/exhibitors/speakers/Jordi Saldo.jpg'),
  'cc_003': require('@/assets/images/exhibitors/speakers/Antonio Jose Trujillo.png'),
  'cc_004': require('@/assets/images/exhibitors/speakers/Inmaculada Ponte Marull.jpeg'),
  'cc_005': require('@/assets/images/exhibitors/speakers/Margarida Julia.jpg'),
  'cc_006': require('@/assets/images/exhibitors/speakers/Francisco Valero.jpg'),
  'cc_007': require('@/assets/images/exhibitors/speakers/Jordi Barbe.jpg'),
  'cc_008': require('@/assets/images/exhibitors/speakers/Olga Sanchez.jpg'),
  'cc_009': require('@/assets/images/exhibitors/speakers/Marc Bravo.png'),
  'cc_010': require('@/assets/images/exhibitors/speakers/Arturo Blazquez.png'),
  'cc_011': require('@/assets/images/exhibitors/speakers/Francois_Chauvigne.png'),
  'cc_012': require('@/assets/images/exhibitors/speakers/Joan Cerda.jpg'),
  'cc_013': require('@/assets/images/exhibitors/speakers/20250709_EstherJulian_UAB.jpg'),
  'cc_014': require('@/assets/images/exhibitors/speakers/NRA_2_Foto.jpeg'),
  'cc_015': require('@/assets/images/exhibitors/speakers/Foto_LASA.png'),
  // Comité de Honor
  'ch_01': require('@/assets/images/exhibitors/speakers/diana_morant.jpeg'),
  // Mesa Clausura
  'mc_01': require('@/assets/images/exhibitors/SIN_FOTO.png'),
  'mc_02': require('@/assets/images/exhibitors/speakers/teresa-sanchis.webp'),
  'mc_03': require('@/assets/images/exhibitors/speakers/monicagutierrez.jpg'),
  // Mesa Inaugural
  'mi_01': require('@/assets/images/exhibitors/speakers/alba_tomas.jpg'),
  'mi_02': require('@/assets/images/exhibitors/speakers/Javier_Lafuente.jpeg'),
  'mi_03': require('@/assets/images/exhibitors/speakers/eva-ortega-paino.jpg'),
  // New speakers
  'spk_049': require('@/assets/images/exhibitors/SIN_FOTO.png'),
  'spk_050': require('@/assets/images/exhibitors/SIN_FOTO.png'),
  // Sponsors
  'biz_001': require('@/assets/images/exhibitors/sponsors/Farmandome.webp'),
  'biz_002': require('@/assets/images/exhibitors/sponsors/pharmax.png'),
  'biz_003': require('@/assets/images/exhibitors/sponsors/proteintech.png'),
  'biz_004': require('@/assets/images/exhibitors/sponsors/minoryx.png'),
  'biz_005': require('@/assets/images/exhibitors/sponsors/Sartorius-logo.webp'),
  'biz_006': require('@/assets/images/exhibitors/sponsors/udl.png'),
  'biz_008': require('@/assets/images/exhibitors/sponsors/bepharma.png'),
  'biz_009': require('@/assets/images/exhibitors/sponsors/hipra.jpg'),
  'biz_010': require('@/assets/images/exhibitors/sponsors/splicebio.png'),
  'biz_011': require('@/assets/images/exhibitors/sponsors/uab.png'),
  'biz_012': require('@/assets/images/exhibitors/sponsors/CESIF.png'),
  'biz_013': require('@/assets/images/exhibitors/sponsors/UFV.jpg'),
  'biz_014': require('@/assets/images/exhibitors/sponsors/CEU.png'),
  'biz_015': require('@/assets/images/exhibitors/sponsors/FarmaLeaders.png'),
  'biz_017': require('@/assets/images/exhibitors/sponsors/cervesa_montseny.jpeg'),
  'biz_018': require('@/assets/images/exhibitors/sponsors/iqs.png'),
  'biz_019': require('@/assets/images/exhibitors/sponsors/pharmaevolution.png'),
  'biz_020': require('@/assets/images/exhibitors/sponsors/Kuhner.png'),
  'biz_021': require('@/assets/images/exhibitors/sponsors/logo_3linies_uvic_color.jpg'),
  'biz_022': require('@/assets/images/exhibitors/sponsors/febiotec_color.png'),
  // Organizadores
  'org_022': require('@/assets/images/exhibitors/sponsors/febiotec_color.png'),
  'org_023': require('@/assets/images/exhibitors/sponsors/asbtec.jpg'),
};
