name: Create Production Builds

jobs:
  build_android:
    type: build
    params:
      platform: android
  # build_ios is disabled until Apple Developer account is verified
  # build_ios:
  #   type: build
  #   params:
  #     platform: ios
